<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function home(){
        $data['meta_title'] = 'Nagaldham Farm';
        $data['meta_description'] = 'Nagaldham Farm';

        $products = [
            'Gaushala Products' => [
                ['name' => 'Gir Cow A2 Ghee', 'description' => 'Pure, aromatic and full of natural nutrition.', 'image' => 'assets/img/product-ghee.jpg', 'long_description' => 'Experience the divine richness of our authentic Gir Cow A2 Ghee, meticulously crafted using the traditional Bilona method. Sourced directly from our free-grazing, grass-fed Gir cows, this golden elixir is churned from nutrient-dense A2 milk curd. Unlike mass-produced ghee, our process ensures that all vital nutrients, including Omega-3 and Omega-6 fatty acids, are perfectly preserved. This ghee is not just a culinary delight but a powerful Ayurvedic superfood known to boost immunity, improve digestion, and promote radiant skin. Free from any synthetic additives, preservatives, or artificial colors, it brings an unmistakable aroma and deeply rich flavor to your daily meals. Whether you are using it for sacred rituals, high-heat cooking, or as a holistic health supplement, our Gir Cow A2 Ghee stands as a testament to pure, unadulterated traditional goodness.'],
                ['name' => 'Havan Kanda', 'description' => 'Pure cow dung cakes for havan and pooja.', 'image' => 'assets/img/product-cow-dung.jpg', 'long_description' => 'Our Havan Kanda represents the purest form of spiritual offering, created from the dung of indigenous Gir cows. In Vedic traditions, cow dung from native breeds is considered highly sacred and purifying. These precisely shaped cakes are naturally sun-dried without any chemical binders, ensuring they burn slowly and cleanly during yagnas, havans, and daily pujas. When ignited, they release a natural, earthy fragrance that not only purifies the surrounding air but also creates a deeply meditative and positive environment. Rich in natural anti-bacterial properties, the smoke from our Havan Kanda helps in cleansing the atmosphere of harmful microbes. Embrace the ancient wisdom of spiritual purification and invite peace, prosperity, and divine energy into your home with these meticulously prepared sacred offerings.'],
                ['name' => 'Dhupbatti', 'description' => 'Natural fragrance for a divine atmosphere.', 'image' => 'assets/img/product-cow-dung.jpg', 'long_description' => 'Transform your living space into a serene sanctuary with our natural cow dung based Dhupbatti. Expertly hand-rolled by combining pure Gir cow dung with a harmonious blend of sacred herbs, natural resins, and aromatic spices, this dhupbatti offers a completely chemical-free aromatic experience. Unlike commercial incense sticks that release toxic fumes and synthetic perfumes, our Dhupbatti burns with a clean, therapeutic smoke that cleanses the environment and eliminates negative energies. The soothing, earthy fragrance acts as a powerful stress reliever, making it perfect for meditation, yoga practices, or simply unwinding after a long day. Experience a profound sense of tranquility and spiritual upliftment while knowing you are using a product that is entirely sustainable, eco-friendly, and deeply rooted in Ayurvedic traditions.'],
                ['name' => 'Cow Dung', 'description' => 'Natural, eco-friendly and multipurpose.', 'image' => 'assets/img/product-cow-dung.jpg', 'long_description' => 'Discover the incredible versatility of our 100% natural, sun-dried Gir Cow Dung. Sourced from our organically fed, happy Gir cows, this product is an essential component for both spiritual practices and sustainable agriculture. In traditional Indian households, it is revered for its purifying properties and used extensively in havans, agnihotra, and daily rituals. Beyond its spiritual significance, it serves as a highly potent, organic fertilizer that breathes life back into depleted soils, enriching them with essential macro and micro-nutrients. Free from any chemical residues, it promotes vigorous plant growth and a robust, healthy garden. Furthermore, its natural anti-bacterial and anti-fungal properties make it an excellent eco-friendly alternative for traditional flooring and wall plastering in sustainable homes.'],
                ['name' => 'Colostrum Powder', 'description' => 'Rich in immunity and essential nutrients.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Nourish your body with nature\'s most powerful immune-boosting superfood—our premium Colostrum Powder. Harvested ethically from Gir cows only after the calf has received its full share, this \'liquid gold\' is gently processed into a fine powder to retain its maximum nutritional potency. Colostrum is exceptionally rich in immunoglobulins (antibodies), lactoferrin, and vital growth factors that work synergistically to fortify your immune system, heal the gut lining, and promote rapid cellular repair. Ideal for growing children, athletes, and adults seeking a natural health shield, it provides an unparalleled defense against seasonal ailments and infections. Completely free from synthetic hormones and antibiotics, our colostrum powder is a pure, concentrated dose of maternal vitality and holistic wellness.']
            ],
            'Sweets' => [
                ['name' => 'Mohanthal', 'description' => 'Traditional Gujarati sweet made with pure ghee.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Indulge in the royal taste of Gujarat with our authentic, handcrafted Mohanthal. Made from premium quality, coarsely ground besan (gram flour), perfectly roasted in our signature Gir Cow A2 Ghee, and sweetened to perfection, this traditional fudge is an absolute delight for your senses. We use only the finest natural ingredients, including pure saffron, aromatic cardamom, and crunchy dry fruits, avoiding any artificial colors or preservatives. The slow-roasting process ensures a rich, grainy texture that instantly melts in your mouth, leaving a lingering, decadent aftertaste. Perfect for festive celebrations, gifting, or satisfying your sweet cravings, our Mohanthal is a nostalgic journey back to your grandmother\'s kitchen, bringing you the authentic, uncompromised flavors of cultural heritage.'],
                ['name' => 'Cow Milk Mava', 'description' => 'Fresh and pure mava for delicious sweets.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Experience the rich, creamy authenticity of our pure Cow Milk Mava (Khoya). Prepared by slowly simmering farm-fresh Gir cow milk over a traditional wood fire, this mava captures the true essence of natural dairy. The slow-reduction process caramelizes the natural milk sugars, resulting in a naturally sweet, incredibly soft, and slightly granular texture that is impossible to replicate with commercial machines. Completely free from adulterants, vegetable fats, or milk powders, it serves as the perfect, high-quality base for a myriad of traditional Indian sweets like gulab jamuns, pedas, and barfis. Elevate your homemade desserts with the rich, unadulterated flavor and wholesome nutrition of our premium, handcrafted mava.'],
                ['name' => 'Mava Peda', 'description' => 'Rich, soft, and delicious mava pedas.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Savor the divine sweetness of our traditional Mava Peda, a classic Indian confection that embodies pure joy. Handcrafted using our own freshly made, slow-cooked Gir cow milk mava and our premium A2 ghee, these pedas are a testament to quality and taste. Delicately infused with premium saffron strands and aromatic cardamom powder, each peda offers a incredibly soft, melt-in-the-mouth experience. We strictly avoid the use of artificial essences, preservatives, or synthetic food colors, ensuring that every bite you take is completely natural and wholesome. Perfect as a sacred offering (prasad) or a delightful treat for your loved ones, our Mava Peda delivers an authentic, rich taste that celebrates the true spirit of Indian festivities.'],
                ['name' => 'Topra Pak', 'description' => 'Coconut sweet made with pure milk and ghee.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Treat yourself to the luscious, tropical flavors of our classic Topra Pak. This exquisite coconut fudge is lovingly prepared using freshly grated, high-quality coconut, gently cooked with pure Gir cow milk and our signature A2 ghee. The careful slow-cooking process ensures that the coconut retains its natural moisture and crunch, while absorbing the rich, creamy sweetness of the milk and ghee. Delicately flavored with nutmeg and cardamom, our Topra Pak boasts a unique, slightly chewy texture and a deeply satisfying taste. Made without any artificial additives or preservatives, it is a healthy, energy-boosting sweet that perfectly balances traditional taste with wholesome nutrition, making it a favorite among all age groups.'],
                ['name' => 'Peanut Pak', 'description' => 'Nutritious peanut sweet for healthy snacking.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Energize your day with the wholesome, crunchy goodness of our Peanut Pak. Crafted from carefully selected, premium quality peanuts roasted to absolute perfection, this traditional sweet is a powerhouse of natural protein and healthy fats. We blend the roasted peanuts with pure jaggery and a touch of our Gir cow A2 ghee, completely eliminating the use of refined sugar and artificial binding agents. The result is a delightfully crunchy, naturally sweet treat that provides a sustained energy boost, making it an ideal guilt-free snack for both children and adults. Celebrate the authentic, rustic flavors of rural traditions while nourishing your body with this incredibly healthy and satisfying delicacy.'],
                ['name' => 'Sesame Chikki', 'description' => 'Crunchy and healthy sesame bites.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Enjoy the perfect crunch and immense health benefits of our traditional Sesame Chikki (Til Chikki). Made using premium, thoroughly cleaned sesame seeds and pure, mineral-rich jaggery, this classic winter sweet is a nutritional powerhouse. Sesame seeds are naturally rich in calcium, iron, and essential fatty acids, while jaggery aids in digestion and provides an instant energy lift. We prepare our chikki in small batches to ensure the perfect, crisp texture without being overly hard. Free from liquid glucose, refined sugars, or artificial preservatives, our Sesame Chikki offers a deliciously authentic, nutty flavor that keeps you warm, healthy, and energized during cold weather or anytime you need a nutritious snack.'],
                ['name' => 'Peanut Chikki', 'description' => 'Classic Indian sweet brittle with roasted peanuts.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Relish the classic, irresistible crunch of our handcrafted Peanut Chikki. Using only the highest quality, perfectly roasted peanuts and pure, unrefined jaggery, we bring you a traditional Indian brittle that is as nutritious as it is delicious. Our careful preparation method ensures that the peanuts remain crisp and flavorful, perfectly enveloped in the rich, earthy sweetness of natural jaggery. We strictly avoid the use of liquid glucose, artificial colors, or chemical preservatives, offering you a completely natural, protein-rich snack. Ideal for satisfying mid-day hunger pangs, boosting energy levels, or simply indulging in a wholesome sweet treat, our Peanut Chikki is a timeless favorite for everyone.'],
                ['name' => 'Besan Ladoo', 'description' => 'Roasted besan ladoos with pure Gir cow ghee.', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Indulge in the timeless, comforting taste of our traditional Besan Ladoo. Handcrafted with immense care, we use premium quality, coarse gram flour (besan) and slow-roast it to golden perfection in generous amounts of our pure Gir Cow A2 Ghee. This meticulous roasting process eliminates any raw taste and brings out a deeply aromatic, nutty flavor that is truly irresistible. Sweetened perfectly and delicately spiced with premium cardamom and garnished with crunchy almonds, our ladoos offer a rich, grainy texture that instantly melts in the mouth. Completely free from artificial colors and preservatives, these ladoos are not just sweets; they are a warm, nostalgic embrace of pure, homemade goodness.']
            ],
            'Organic Farm Products' => [
                ['name' => 'Bansi Wheat', 'description' => 'Premium quality Bansi wheat for healthy rotis.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Experience the exceptional nutritional profile and rich, robust flavor of our premium Bansi Wheat. Grown naturally on our organic farms without the use of any synthetic pesticides, herbicides, or chemical fertilizers, this traditional wheat variety is highly revered for its superior quality. Bansi wheat is naturally rich in dietary fiber, essential complex carbohydrates, and vital minerals, making it an excellent choice for a healthy, balanced diet. The grains are carefully harvested, cleaned, and sorted to ensure you receive nothing but the best. Flour made from our Bansi wheat yields incredibly soft, flavorful, and highly nutritious rotis that stay fresh longer. Embrace a healthier lifestyle with this pure, unadulterated staple.'],
                ['name' => 'Tukda Wheat', 'description' => 'High-quality Tukda wheat, rich in fiber.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Nourish your family with the wholesome, natural goodness of our premium Tukda Wheat. Cultivated using sustainable, organic farming practices, this superior wheat variety is completely free from harmful chemicals and synthetic additives. Known for its distinct, slightly coarse texture and excellent nutritional value, Tukda wheat is particularly rich in dietary fiber, aiding in healthy digestion and sustained energy release. We take great care in the harvesting and cleaning process to preserve the natural bran and germ, ensuring maximum health benefits. Whether used for making hearty flatbreads, nutritious porridge, or wholesome baked goods, our Tukda Wheat brings the authentic, earthy taste of nature directly to your dining table.'],
                ['name' => 'Chana', 'description' => 'Organic and protein-rich whole chana.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Boost your daily protein intake with our premium, organically grown whole Chana (Bengal Gram). Cultivated on our chemical-free farms, these legumes are a powerhouse of essential plant-based protein, dietary fiber, complex carbohydrates, and vital minerals like iron and folate. We employ rigorous, natural sorting methods to ensure that only the healthiest, unpolished grains reach your kitchen, preserving their natural oils, robust flavor, and maximum nutritional content. Ideal for a wide variety of traditional recipes, including hearty curries, nutritious salads, and healthy sprouts, our Chana cooks beautifully and offers a deeply satisfying, earthy taste. Make a conscious choice for your health and the environment with our pure, sustainable produce.'],
                ['name' => 'Chana Dal', 'description' => 'Unpolished Chana dal for daily nutrition.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Incorporate the wholesome nutrition of our pure, unpolished Chana Dal into your daily meals. Sourced from organically grown Bengal gram, our dal is minimally processed to retain its natural dietary fiber, essential plant-based protein, and vital micronutrients. Unlike polished dals that lose their nutritional value and natural taste, our Chana Dal offers a rich, earthy flavor and a satisfying, hearty texture when cooked. It is an indispensable staple for preparing traditional Indian dishes, from comforting dal tadka to savory snacks. Cultivated strictly without the use of synthetic pesticides or chemical fertilizers, it is a healthy, safe, and incredibly delicious choice for you and your family.'],
                ['name' => 'Moong', 'description' => 'Fresh organic green moong beans.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Experience the pure, easily digestible goodness of our organically grown whole Green Moong. Cultivated with utmost care on our sustainable farms, these tiny green beans are incredibly rich in high-quality plant protein, dietary fiber, and essential vitamins and minerals. Completely free from harmful chemicals, synthetic fertilizers, and artificial polishing, our Moong retains its natural, vibrant green color and exceptional nutritional profile. It is highly versatile and perfect for making highly nutritious sprouts, wholesome curries, comforting khichdi, or healthy salads. Known in Ayurveda for its cooling and detoxifying properties, our Green Moong is a perfect addition to a balanced, health-conscious diet.'],
                ['name' => 'Moong Dal', 'description' => 'Healthy and easy-to-digest moong dal.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Enjoy the light, soothing, and highly nutritious qualities of our premium, unpolished Moong Dal. Made from organically cultivated green moong, this split yellow dal is minimally processed to ensure it retains its natural fiber, essential proteins, and vital nutrients. Renowned for being exceptionally easy to digest, it is widely recommended for all age groups, from infants to the elderly. Because it is completely unpolished and free from any chemical treatments or artificial colors, it delivers an authentic, mild, and naturally sweet flavor. Perfect for making comforting dal fry, wholesome khichdi, or nutritious sweets, our Moong Dal is a staple of pure health and simplicity.'],
                ['name' => 'Turmeric', 'description' => 'Pure organic turmeric powder with high curcumin.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Elevate your health and cooking with the vibrant color and potent healing properties of our pure, organic Turmeric Powder. Grown naturally in our chemical-free farms, our turmeric is harvested at peak maturity and carefully sun-dried to preserve its high curcumin content—the active compound responsible for its remarkable anti-inflammatory and antioxidant benefits. We grind the turmeric roots at low temperatures to ensure the natural essential oils and intense flavor remain fully intact. Completely free from synthetic dyes, adulterants, or preservatives, it adds a rich, golden hue and a deep, earthy aroma to your dishes. Incorporate this powerful Ayurvedic superfood into your daily meals, teas, or wellness drinks for optimal holistic health.'],
                ['name' => 'Groundnut Oil', 'description' => 'Cold-pressed groundnut oil for healthy cooking.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Rediscover the authentic taste and immense health benefits of our traditional, cold-pressed Groundnut Oil. Extracted slowly using wooden ghanis (Chekku) from premium, organically grown peanuts, this oil is completely unrefined, unbleached, and free from any chemical processing. The cold-pressing technique ensures that all the natural antioxidants, vital nutrients, and heart-healthy monounsaturated fats are perfectly preserved. It boasts a rich, nutty aroma and a high smoke point, making it exceptionally versatile and ideal for all types of Indian cooking, including deep-frying and sautéing. Choose our pure Groundnut Oil for a healthier heart, glowing skin, and incredibly flavorful meals.'],
                ['name' => 'Sesame Oil', 'description' => '100% pure cold-pressed sesame oil.', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Nourish your body inside and out with our 100% pure, cold-pressed Sesame Oil. Extracted from premium, organically cultivated sesame seeds using traditional wooden ghani methods, this oil is completely unrefined and free from any chemical additives. Highly revered in Ayurveda as \'the king of oils,\' it is extraordinarily rich in antioxidants, essential fatty acids, and vital nutrients like Vitamin E. The cold-pressing process ensures it retains its deep, natural golden color and distinctly rich, nutty flavor. Whether used for healthy culinary applications, therapeutic body massages, or holistic Ayurvedic practices like oil pulling, our Sesame Oil offers unparalleled purity and profound health benefits.']
            ]
        ];
                return view('front.home', compact('data', 'products'));
    }

    public function product(){
        $data['meta_title'] = 'Products - Nagaldham Farm';
        $data['meta_description'] = 'Discover the goodness of our Gaushala and organic farm products. Nourishing your family with purity, tradition and the natural care of our Gir cows.';

        $categories = [
            ['name' => 'Gaushala Products', 'count' => 5, 'image' => 'assets/img/product-ghee.jpg', 'long_description' => 'Experience the unparalleled purity and authenticity of our Gaushala Products.'],
            ['name' => 'Sweets', 'count' => 8, 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Experience the unparalleled purity and authenticity of our Sweets.'],
            ['name' => 'Organic Farm Products', 'count' => 9, 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Experience the unparalleled purity and authenticity of our Organic Farm Products.']
        ];

        $allProducts = [
            ['name' => 'Gir Cow A2 Ghee', 'category' => 'Gaushala Products', 'description' => 'Pure, aromatic and full of natural goodness.', 'price' => '1,250', 'rating' => '4.8', 'image' => 'assets/img/product-ghee.jpg', 'long_description' => 'Experience the divine richness of our authentic Gir Cow A2 Ghee, meticulously crafted using the traditional Bilona method. Sourced directly from our free-grazing, grass-fed Gir cows, this golden elixir is churned from nutrient-dense A2 milk curd. Unlike mass-produced ghee, our process ensures that all vital nutrients, including Omega-3 and Omega-6 fatty acids, are perfectly preserved. This ghee is not just a culinary delight but a powerful Ayurvedic superfood known to boost immunity, improve digestion, and promote radiant skin. Free from any synthetic additives, preservatives, or artificial colors, it brings an unmistakable aroma and deeply rich flavor to your daily meals. Whether you are using it for sacred rituals, high-heat cooking, or as a holistic health supplement, our Gir Cow A2 Ghee stands as a testament to pure, unadulterated traditional goodness.'],
            ['name' => 'Havan Kanda', 'category' => 'Gaushala Products', 'description' => 'Pure cow dung cakes for havan and pooja.', 'price' => '150', 'rating' => '4.6', 'image' => 'assets/img/product-cow-dung.jpg', 'long_description' => 'Our Havan Kanda represents the purest form of spiritual offering, created from the dung of indigenous Gir cows. In Vedic traditions, cow dung from native breeds is considered highly sacred and purifying. These precisely shaped cakes are naturally sun-dried without any chemical binders, ensuring they burn slowly and cleanly during yagnas, havans, and daily pujas. When ignited, they release a natural, earthy fragrance that not only purifies the surrounding air but also creates a deeply meditative and positive environment. Rich in natural anti-bacterial properties, the smoke from our Havan Kanda helps in cleansing the atmosphere of harmful microbes. Embrace the ancient wisdom of spiritual purification and invite peace, prosperity, and divine energy into your home with these meticulously prepared sacred offerings.'],
            ['name' => 'Dhupbatti', 'category' => 'Gaushala Products', 'description' => 'Natural cow dung based dhupbatti for pure fragrance.', 'price' => '120', 'rating' => '4.7', 'image' => 'assets/img/product-cow-dung.jpg', 'long_description' => 'Transform your living space into a serene sanctuary with our natural cow dung based Dhupbatti. Expertly hand-rolled by combining pure Gir cow dung with a harmonious blend of sacred herbs, natural resins, and aromatic spices, this dhupbatti offers a completely chemical-free aromatic experience. Unlike commercial incense sticks that release toxic fumes and synthetic perfumes, our Dhupbatti burns with a clean, therapeutic smoke that cleanses the environment and eliminates negative energies. The soothing, earthy fragrance acts as a powerful stress reliever, making it perfect for meditation, yoga practices, or simply unwinding after a long day. Experience a profound sense of tranquility and spiritual upliftment while knowing you are using a product that is entirely sustainable, eco-friendly, and deeply rooted in Ayurvedic traditions.'],
            ['name' => 'Cow Dung', 'category' => 'Gaushala Products', 'description' => '100% natural cow dung for various uses.', 'price' => '80', 'rating' => '4.5', 'image' => 'assets/img/product-cow-dung.jpg', 'long_description' => 'Discover the incredible versatility of our 100% natural, sun-dried Gir Cow Dung. Sourced from our organically fed, happy Gir cows, this product is an essential component for both spiritual practices and sustainable agriculture. In traditional Indian households, it is revered for its purifying properties and used extensively in havans, agnihotra, and daily rituals. Beyond its spiritual significance, it serves as a highly potent, organic fertilizer that breathes life back into depleted soils, enriching them with essential macro and micro-nutrients. Free from any chemical residues, it promotes vigorous plant growth and a robust, healthy garden. Furthermore, its natural anti-bacterial and anti-fungal properties make it an excellent eco-friendly alternative for traditional flooring and wall plastering in sustainable homes.'],
            
            ['name' => 'Colostrum Powder', 'category' => 'Gaushala Products', 'description' => 'Rich in immunity and essential nutrients.', 'price' => '850', 'rating' => '4.8', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Nourish your body with nature\'s most powerful immune-boosting superfood—our premium Colostrum Powder. Harvested ethically from Gir cows only after the calf has received its full share, this \'liquid gold\' is gently processed into a fine powder to retain its maximum nutritional potency. Colostrum is exceptionally rich in immunoglobulins (antibodies), lactoferrin, and vital growth factors that work synergistically to fortify your immune system, heal the gut lining, and promote rapid cellular repair. Ideal for growing children, athletes, and adults seeking a natural health shield, it provides an unparalleled defense against seasonal ailments and infections. Completely free from synthetic hormones and antibiotics, our colostrum powder is a pure, concentrated dose of maternal vitality and holistic wellness.'],
            ['name' => 'Mohanthal', 'category' => 'Sweets', 'description' => 'Traditional Gujarati sweet with rich taste.', 'price' => '350', 'rating' => '4.9', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Indulge in the royal taste of Gujarat with our authentic, handcrafted Mohanthal. Made from premium quality, coarsely ground besan (gram flour), perfectly roasted in our signature Gir Cow A2 Ghee, and sweetened to perfection, this traditional fudge is an absolute delight for your senses. We use only the finest natural ingredients, including pure saffron, aromatic cardamom, and crunchy dry fruits, avoiding any artificial colors or preservatives. The slow-roasting process ensures a rich, grainy texture that instantly melts in your mouth, leaving a lingering, decadent aftertaste. Perfect for festive celebrations, gifting, or satisfying your sweet cravings, our Mohanthal is a nostalgic journey back to your grandmother\'s kitchen, bringing you the authentic, uncompromised flavors of cultural heritage.'],
            ['name' => 'Cow Milk Mava', 'category' => 'Sweets', 'description' => 'Made from pure cow milk.', 'price' => '380', 'rating' => '4.8', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Experience the rich, creamy authenticity of our pure Cow Milk Mava (Khoya). Prepared by slowly simmering farm-fresh Gir cow milk over a traditional wood fire, this mava captures the true essence of natural dairy. The slow-reduction process caramelizes the natural milk sugars, resulting in a naturally sweet, incredibly soft, and slightly granular texture that is impossible to replicate with commercial machines. Completely free from adulterants, vegetable fats, or milk powders, it serves as the perfect, high-quality base for a myriad of traditional Indian sweets like gulab jamuns, pedas, and barfis. Elevate your homemade desserts with the rich, unadulterated flavor and wholesome nutrition of our premium, handcrafted mava.'],
            ['name' => 'Mava Peda', 'category' => 'Sweets', 'description' => 'Soft and delicious traditional peda.', 'price' => '360', 'rating' => '4.7', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Savor the divine sweetness of our traditional Mava Peda, a classic Indian confection that embodies pure joy. Handcrafted using our own freshly made, slow-cooked Gir cow milk mava and our premium A2 ghee, these pedas are a testament to quality and taste. Delicately infused with premium saffron strands and aromatic cardamom powder, each peda offers a incredibly soft, melt-in-the-mouth experience. We strictly avoid the use of artificial essences, preservatives, or synthetic food colors, ensuring that every bite you take is completely natural and wholesome. Perfect as a sacred offering (prasad) or a delightful treat for your loved ones, our Mava Peda delivers an authentic, rich taste that celebrates the true spirit of Indian festivities.'],
            
            ['name' => 'Topra Pak', 'category' => 'Sweets', 'description' => 'Rich coconut based traditional sweet.', 'price' => '340', 'rating' => '4.6', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Treat yourself to the luscious, tropical flavors of our classic Topra Pak. This exquisite coconut fudge is lovingly prepared using freshly grated, high-quality coconut, gently cooked with pure Gir cow milk and our signature A2 ghee. The careful slow-cooking process ensures that the coconut retains its natural moisture and crunch, while absorbing the rich, creamy sweetness of the milk and ghee. Delicately flavored with nutmeg and cardamom, our Topra Pak boasts a unique, slightly chewy texture and a deeply satisfying taste. Made without any artificial additives or preservatives, it is a healthy, energy-boosting sweet that perfectly balances traditional taste with wholesome nutrition, making it a favorite among all age groups.'],
            ['name' => 'Peanut Pak', 'category' => 'Sweets', 'description' => 'Crunchy and healthy peanut sweet.', 'price' => '280', 'rating' => '4.7', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Energize your day with the wholesome, crunchy goodness of our Peanut Pak. Crafted from carefully selected, premium quality peanuts roasted to absolute perfection, this traditional sweet is a powerhouse of natural protein and healthy fats. We blend the roasted peanuts with pure jaggery and a touch of our Gir cow A2 ghee, completely eliminating the use of refined sugar and artificial binding agents. The result is a delightfully crunchy, naturally sweet treat that provides a sustained energy boost, making it an ideal guilt-free snack for both children and adults. Celebrate the authentic, rustic flavors of rural traditions while nourishing your body with this incredibly healthy and satisfying delicacy.'],
            ['name' => 'Sesame Chikki', 'category' => 'Sweets', 'description' => 'Nutritious and tasty til chikki.', 'price' => '260', 'rating' => '4.7', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Enjoy the perfect crunch and immense health benefits of our traditional Sesame Chikki (Til Chikki). Made using premium, thoroughly cleaned sesame seeds and pure, mineral-rich jaggery, this classic winter sweet is a nutritional powerhouse. Sesame seeds are naturally rich in calcium, iron, and essential fatty acids, while jaggery aids in digestion and provides an instant energy lift. We prepare our chikki in small batches to ensure the perfect, crisp texture without being overly hard. Free from liquid glucose, refined sugars, or artificial preservatives, our Sesame Chikki offers a deliciously authentic, nutty flavor that keeps you warm, healthy, and energized during cold weather or anytime you need a nutritious snack.'],
            ['name' => 'Peanut Chikki', 'category' => 'Sweets', 'description' => 'Traditional peanut chikki with natural sweetness.', 'price' => '260', 'rating' => '4.6', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Relish the classic, irresistible crunch of our handcrafted Peanut Chikki. Using only the highest quality, perfectly roasted peanuts and pure, unrefined jaggery, we bring you a traditional Indian brittle that is as nutritious as it is delicious. Our careful preparation method ensures that the peanuts remain crisp and flavorful, perfectly enveloped in the rich, earthy sweetness of natural jaggery. We strictly avoid the use of liquid glucose, artificial colors, or chemical preservatives, offering you a completely natural, protein-rich snack. Ideal for satisfying mid-day hunger pangs, boosting energy levels, or simply indulging in a wholesome sweet treat, our Peanut Chikki is a timeless favorite for everyone.'],

            ['name' => 'Besan Ladoo', 'category' => 'Sweets', 'description' => 'Traditional besan ladoo made with purity.', 'price' => '320', 'rating' => '4.8', 'image' => 'assets/img/product-sweets.jpg', 'long_description' => 'Indulge in the timeless, comforting taste of our traditional Besan Ladoo. Handcrafted with immense care, we use premium quality, coarse gram flour (besan) and slow-roast it to golden perfection in generous amounts of our pure Gir Cow A2 Ghee. This meticulous roasting process eliminates any raw taste and brings out a deeply aromatic, nutty flavor that is truly irresistible. Sweetened perfectly and delicately spiced with premium cardamom and garnished with crunchy almonds, our ladoos offer a rich, grainy texture that instantly melts in the mouth. Completely free from artificial colors and preservatives, these ladoos are not just sweets; they are a warm, nostalgic embrace of pure, homemade goodness.'],
            ['name' => 'Bansi Wheat', 'category' => 'Organic Farm Products', 'description' => 'High quality traditional wheat grain.', 'price' => '80', 'rating' => '4.5', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Experience the exceptional nutritional profile and rich, robust flavor of our premium Bansi Wheat. Grown naturally on our organic farms without the use of any synthetic pesticides, herbicides, or chemical fertilizers, this traditional wheat variety is highly revered for its superior quality. Bansi wheat is naturally rich in dietary fiber, essential complex carbohydrates, and vital minerals, making it an excellent choice for a healthy, balanced diet. The grains are carefully harvested, cleaned, and sorted to ensure you receive nothing but the best. Flour made from our Bansi wheat yields incredibly soft, flavorful, and highly nutritious rotis that stay fresh longer. Embrace a healthier lifestyle with this pure, unadulterated staple.'],
            ['name' => 'Tukda Wheat', 'category' => 'Organic Farm Products', 'description' => 'Nutritious tukda wheat for daily use.', 'price' => '75', 'rating' => '4.4', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Nourish your family with the wholesome, natural goodness of our premium Tukda Wheat. Cultivated using sustainable, organic farming practices, this superior wheat variety is completely free from harmful chemicals and synthetic additives. Known for its distinct, slightly coarse texture and excellent nutritional value, Tukda wheat is particularly rich in dietary fiber, aiding in healthy digestion and sustained energy release. We take great care in the harvesting and cleaning process to preserve the natural bran and germ, ensuring maximum health benefits. Whether used for making hearty flatbreads, nutritious porridge, or wholesome baked goods, our Tukda Wheat brings the authentic, earthy taste of nature directly to your dining table.'],
            ['name' => 'Chana', 'category' => 'Organic Farm Products', 'description' => 'Premium quality chana grains.', 'price' => '90', 'rating' => '4.6', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Boost your daily protein intake with our premium, organically grown whole Chana (Bengal Gram). Cultivated on our chemical-free farms, these legumes are a powerhouse of essential plant-based protein, dietary fiber, complex carbohydrates, and vital minerals like iron and folate. We employ rigorous, natural sorting methods to ensure that only the healthiest, unpolished grains reach your kitchen, preserving their natural oils, robust flavor, and maximum nutritional content. Ideal for a wide variety of traditional recipes, including hearty curries, nutritious salads, and healthy sprouts, our Chana cooks beautifully and offers a deeply satisfying, earthy taste. Make a conscious choice for your health and the environment with our pure, sustainable produce.'],

            ['name' => 'Chana Dal', 'category' => 'Organic Farm Products', 'description' => 'Rich in protein and natural nutrition.', 'price' => '110', 'rating' => '4.6', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Incorporate the wholesome nutrition of our pure, unpolished Chana Dal into your daily meals. Sourced from organically grown Bengal gram, our dal is minimally processed to retain its natural dietary fiber, essential plant-based protein, and vital micronutrients. Unlike polished dals that lose their nutritional value and natural taste, our Chana Dal offers a rich, earthy flavor and a satisfying, hearty texture when cooked. It is an indispensable staple for preparing traditional Indian dishes, from comforting dal tadka to savory snacks. Cultivated strictly without the use of synthetic pesticides or chemical fertilizers, it is a healthy, safe, and incredibly delicious choice for you and your family.'],
            ['name' => 'Moong', 'category' => 'Organic Farm Products', 'description' => 'Pure and high quality moong grains.', 'price' => '120', 'rating' => '4.7', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Experience the pure, easily digestible goodness of our organically grown whole Green Moong. Cultivated with utmost care on our sustainable farms, these tiny green beans are incredibly rich in high-quality plant protein, dietary fiber, and essential vitamins and minerals. Completely free from harmful chemicals, synthetic fertilizers, and artificial polishing, our Moong retains its natural, vibrant green color and exceptional nutritional profile. It is highly versatile and perfect for making highly nutritious sprouts, wholesome curries, comforting khichdi, or healthy salads. Known in Ayurveda for its cooling and detoxifying properties, our Green Moong is a perfect addition to a balanced, health-conscious diet.'],
            ['name' => 'Moong Dal', 'category' => 'Organic Farm Products', 'description' => 'Healthy and easily digestible moong dal.', 'price' => '140', 'rating' => '4.7', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Enjoy the light, soothing, and highly nutritious qualities of our premium, unpolished Moong Dal. Made from organically cultivated green moong, this split yellow dal is minimally processed to ensure it retains its natural fiber, essential proteins, and vital nutrients. Renowned for being exceptionally easy to digest, it is widely recommended for all age groups, from infants to the elderly. Because it is completely unpolished and free from any chemical treatments or artificial colors, it delivers an authentic, mild, and naturally sweet flavor. Perfect for making comforting dal fry, wholesome khichdi, or nutritious sweets, our Moong Dal is a staple of pure health and simplicity.'],
            ['name' => 'Turmeric', 'category' => 'Organic Farm Products', 'description' => 'Natural turmeric for better health.', 'price' => '180', 'rating' => '4.8', 'image' => 'assets/img/product-colostrum.jpg', 'long_description' => 'Elevate your health and cooking with the vibrant color and potent healing properties of our pure, organic Turmeric Powder. Grown naturally in our chemical-free farms, our turmeric is harvested at peak maturity and carefully sun-dried to preserve its high curcumin content—the active compound responsible for its remarkable anti-inflammatory and antioxidant benefits. We grind the turmeric roots at low temperatures to ensure the natural essential oils and intense flavor remain fully intact. Completely free from synthetic dyes, adulterants, or preservatives, it adds a rich, golden hue and a deep, earthy aroma to your dishes. Incorporate this powerful Ayurvedic superfood into your daily meals, teas, or wellness drinks for optimal holistic health.']
        ];
        return view('front.product', compact('data', 'categories', 'allProducts'));
    }
}